### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by jmiggs** [jmiggs/RobinStax#2]
# User Auth
​
## Functionality
​
- [x] The main button with logo should link to `/`
- [x] Has working demo login
- [x] Smooth, bug free navigation
​
### Before Login
​
- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user
​
### After Login
​
- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in
​
​
## Style
​
- [x] The site should look exactly like the actual site
- [ ] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [ ] Remove Redux logger and all console.log()'s from production
​
## Seeds
- [x] Adequate and appropriate seeds

**Comment by jmiggs** [comment]
I didnt realize i had to hit the check box

**Comment by ronilbhatia** [comment]
Hey Miguel, great job - the styling looks awesome! A couple of minor comments, stylewise, but other than that you are good to go!

1. There's an 8px white border around the entire page - this is because of default styling on the browser. Not sure if you already have one but you should make a CSS reset file - there's a bunch of reset files you can find online that you can use (they should include credits for their author, make sure to include those). For this one in particular you just need to set `margin: 0` on the body.
2. Add `cursor: pointer` to your form buttons (sign up, sign in & demo). Also add a hover effect that changes the color a bit to make the button appear even more clickable. Finally it would look cleaner if you capitalized the words as 'Sign Up', 'Login', and 'Demo' instead.
3. I'd like to not have to click 'login' after I click demo. Set the demo login up to directly log the user in as the demo user.
4. You're own border that you've set on the input fields gets messed up by the outline. You can get rid of this by setting `outline: none` on the inputs. Note that the outline is built-in to browsers as an accessibility thing but since you have your own border that you add on focus it is okay to remove.

**Comment by jmiggs** [comment]
auth implemented completely
